# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('tags', models.CharField(max_length=300)),
                ('number_of_views', models.IntegerField()),
            ],
        ),
    ]
