# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_api', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
