# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_api', '0003_auto_20170101_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
