# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_api', '0004_auto_20170102_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
